export const datas = [
  {
    content: [
      {
        key: "MARUTI",
        value: "Maruti",
      },
      { key: "HYUNDAI", value: "Hyundai" },
      { key: "HONDA", value: "Honda" },
      { key: "TATA", value: "Tata" },
      { key: "TOYOTA", value: "Toyota" },
      { key: "CHEVROLET", value: "Chevrolet" },
      { key: "FORD", value: "Ford" },
      { key: "MAHINDRA", value: "Mahindra" },
      { key: "SKODA", value: "Skoda" },
      { key: "VOLKSWAGEN", value: "Volkswagen" },
      { key: "NISSAN", value: "Nissan" },
      { key: "RENAULT", value: "Renault" },
      { key: "FIAT", value: "Fiat" },
      { key: "MERCEDES BENZ", value: "Mercedes Benz" },
      { key: "BMW", value: "BMW" },
      { key: "AUDI", value: "Audi" },
      { key: "DATSUN", value: "Datsun" },
      { key: "MARUTI SWIFT DZIRE", value: "Maruti Swift Dzire" },
      { key: "MARUTI SWIFT", value: "Maruti Swift" },
      { key: "MARUTI ALTO", value: "Maruti Alto" },
      { key: "MARUTI WAGON R", value: "Maruti Wagon R" },
      { key: "MARUTI BALENO", value: "Maruti Baleno" },
      { key: "MARUTI CIAZ", value: "Maruti Ciaz" },
      { key: "HYUNDAI I20", value: "Hyundai i20" },
      { key: "HYUNDAI I10", value: "Hyundai i10" },
      { key: "HYUNDAI VERNA", value: "Hyundai Verna" },
      { key: "HONDA CITY", value: "Honda City" },
      { key: "HONDA AMAZE", value: "Honda Amaze" },
      { key: "HONDA JAZZ", value: "Honda Jazz" },
      { key: "HONDA BRIO", value: "Honda Brio" },
      { key: "CHEVROLET BEAT", value: "Chevrolet Beat" },
      { key: "RENAULT KWID", value: "Renault Kwid" },
      { key: "VOLKSWAGEN POLO", value: "Volkswagen Polo" },
      { key: "AUDI A4", value: "Audi A4" },
      { key: "ASHOK LEYLAND STILE", value: "Ashok Leyland Stile" },
      { key: "ASTON MARTIN DB9", value: "Aston Martin DB9" },
      { key: "ASTON MARTIN DBS", value: "Aston Martin DBS" },
      { key: "ASTON MARTIN RAPIDE", value: "Aston Martin Rapide" },
      { key: "ASTON MARTIN V12 VANTAGE", value: "Aston Martin V12 Vantage" },
      { key: "ASTON MARTIN V8 VANTAGE", value: "Aston Martin V8 Vantage" },
      { key: "ASTON MARTIN VANQUISH", value: "Aston Martin Vanquish" },
      { key: "ASTON MARTIN ZAGATO", value: "Aston Martin Zagato" },
      { key: "AUDI A3", value: "Audi A3" },
      { key: "AUDI A6", value: "Audi A6" },
      { key: "AUDI A7", value: "Audi A7" },
      { key: "AUDI A8", value: "Audi A8" },
      { key: "AUDI A8L", value: "Audi A8L" },
      { key: "AUDI Q3", value: "Audi Q3" },
      { key: "AUDI Q5", value: "Audi Q5" },
      { key: "AUDI Q7", value: "Audi Q7" },
      { key: "AUDI R8", value: "Audi R8" },
      { key: "AUDI RS 5", value: "Audi RS 5" },
      { key: "AUDI RS 7", value: "Audi RS 7" },
      { key: "AUDI S6", value: "Audi S6" },
      { key: "AUDI TT", value: "Audi TT" },
      { key: "BENTLEY ARNAGE", value: "Bentley Arnage" },
      { key: "BENTLEY AZURE", value: "Bentley Azure" },
      { key: "BENTLEY CONTINENTAL", value: "Bentley Continental" },
      {
        key: "BENTLEY CONTINENTAL FLYING SPUR",
        value: "Bentley Continental Flying Spur",
      },
      { key: "BENTLEY CONTINENTAL GT", value: "Bentley Continental GT" },
      { key: "BENTLEY CONTINENTAL GTC", value: "Bentley Continental GTC" },
      { key: "BENTLEY MULSANNE", value: "Bentley Mulsanne" },
      { key: "BMW 1 SERIES", value: "BMW 1 Series" },
      { key: "BMW 3 SERIES", value: "BMW 3 Series" },
      { key: "BMW 5 SERIES", value: "BMW 5 Series" },
      { key: "BMW 5 SERIES GT", value: "BMW 5 Series GT" },
      { key: "BMW 6 SERIES", value: "BMW 6 Series" },
      { key: "BMW 7 SERIES", value: "BMW 7 Series" },
      { key: "BMW GRAN TURISMO", value: "BMW Gran Turismo" },
      { key: "BMW I8", value: "BMW i8" },
      { key: "BMW M3", value: "BMW M3" },
      { key: "BMW M5", value: "BMW M5" },
      { key: "BMW M6", value: "BMW M6" },
      { key: "BMW MINI", value: "BMW Mini" },
      { key: "BMW X1", value: "BMW X1" },
      { key: "BMW X3", value: "BMW X3" },
      { key: "BMW X5", value: "BMW X5" },
      { key: "BMW X6", value: "BMW X6" },
      { key: "BMW Z4", value: "BMW Z4" },
      { key: "BUGATTI VEYRON", value: "Bugatti Veyron" },
      { key: "CHEVROLET AVEO", value: "Chevrolet Aveo" },
      { key: "CHEVROLET AVEO U VA", value: "Chevrolet Aveo U-VA" },
      { key: "CHEVROLET CAPTIVA", value: "Chevrolet Captiva" },
      { key: "CHEVROLET CRUZE", value: "Chevrolet Cruze" },
      { key: "CHEVROLET ENJOY", value: "Chevrolet Enjoy" },
      { key: "CHEVROLET FORESTER", value: "Chevrolet Forester" },
      { key: "CHEVROLET OPTRA", value: "Chevrolet Optra" },
      { key: "CHEVROLET OPTRA MAGNUM", value: "Chevrolet Optra Magnum" },
      { key: "CHEVROLET OPTRA SRV", value: "Chevrolet Optra SRV" },
      { key: "CHEVROLET SAIL", value: "Chevrolet Sail" },
      { key: "CHEVROLET SAIL UVA", value: "Chevrolet Sail U-VA" },
      { key: "CHEVROLET SPARK", value: "Chevrolet Spark" },
      { key: "CHEVROLET TAVERA", value: "Chevrolet Tavera" },
      { key: "CHEVROLET TRAILBLAZER", value: "Chevrolet Trailblazer" },
      { key: "DAEWOO CIELO", value: "Daewoo Cielo" },
      { key: "DAEWOO MATIZ", value: "Daewoo Matiz" },
      { key: "DATSUN GO", value: "Datsun Go" },
      { key: "DATSUN GO PLUS", value: "Datsun Go+" },
      { key: "DATSUN REDI GO", value: "Datsun Redi Go" },
      { key: "DC AVANTI", value: "DC Avanti" },
      { key: "FERRARI 458", value: "Ferrari 458" },
      { key: "FERRARI 458 SPIDER", value: "Ferrari 458 Spider" },
      { key: "FERRARI 599 GTB", value: "Ferrari 599 GTB" },
      { key: "FERRARI CALIFORNIA", value: "Ferrari California" },
      { key: "FERRARI F12 BERLINETTA", value: "Ferrari F12 Berlinetta" },
      { key: "FERRARI FF", value: "Ferrari FF" },
      { key: "FIAT 500", value: "Fiat 500" },
      { key: "FIAT ABARTH 595", value: "Fiat Abarth 595" },
      { key: "FIAT ADVENTURE", value: "Fiat Adventure" },
      { key: "FIAT AVVVENTURA", value: "Fiat Avventura" },
      { key: "FIAT GRAND PUNTO", value: "Fiat Grand Punto" },
      { key: "FIAT LINEA", value: "Fiat Linea" },
      { key: "FIAT PALIO", value: "Fiat Palio" },
      { key: "FIAT PALIO D", value: "Fiat Palio D" },
      { key: "FIAT PALIO NV", value: "Fiat Palio NV" },
      { key: "FIAT PALIO STILE", value: "Fiat Palio Stile" },
      { key: "FIAT PETRA", value: "Fiat Petra" },
      { key: "FIAT PETRA D", value: "Fiat Petra D" },
      { key: "FIAT PUNTO EVO", value: "Fiat Punto Evo" },
      { key: "FIAT SIENA", value: "Fiat Siena" },
      { key: "FIAT SIENA WEEKEND", value: "Fiat Siena Weekend" },
      { key: "FIAT UNO", value: "Fiat Uno" },
      { key: "FIAT URBAN CROSS", value: "Fiat Urban Cross" },
      { key: "FORCE MOTORS FORCE ONE", value: "Force Motors Force One" },
      { key: "FORCE MOTORS GURKHA", value: "Force Motors Gurkha" },
      { key: "FORCE MOTORS TRAX CRUISER", value: "Force Motors Trax Cruiser" },
      { key: "FORD CLASSIC", value: "Ford Classic" },
      { key: "FORD ECOSPORT", value: "Ford EcoSport" },
      { key: "FORD ENDEAVOUR", value: "Ford Endeavour" },
      { key: "FORD ESCORT", value: "Ford Escort" },
      { key: "FORD FIESTA", value: "Ford Fiesta" },
      { key: "FORD FIESTA CLASSIC", value: "Ford Fiesta Classic" },
      { key: "FORD FIGO", value: "Ford Figo" },
      { key: "FORD FIGO ASPIRE", value: "Ford Figo Aspire" },
      { key: "FORD FREESTYLE", value: "Ford Freestyle" },
      { key: "FORD FUSION", value: "Ford Fusion" },
      { key: "FORD IKON", value: "Ford Ikon" },
      { key: "FORD JEEP", value: "Ford Jeep" },
      { key: "FORD MONDEO", value: "Ford Mondeo" },
      { key: "FORD NEW FIGO", value: "Ford New Figo" },
      {
        key: "HINDUSTAN MOTORS AMBASSADOR",
        value: "Hindustan Motors Ambassador",
      },
      { key: "HINDUSTAN MOTORS CONTESSA", value: "Hindustan Motors Contessa" },
      { key: "HONDA ACCORD", value: "Honda Accord" },
      { key: "HONDA BR-V", value: "Honda BR-V" },
      { key: "HONDA CITY ZX", value: "Honda City ZX" },
      { key: "HONDA CIVIC", value: "Honda Civic" },
      { key: "HONDA CIVIC HYBRID", value: "Honda Civic Hybrid" },
      { key: "HONDA CRV", value: "Honda CR-V" },
      { key: "HONDA MOBILIO", value: "Honda Mobilio" },
      { key: "HONDA WR-V", value: "Honda WR-V" },
      { key: "HYUNDAI ACCENT", value: "Hyundai Accent" },
      { key: "HYUNDAI CRETA", value: "Hyundai Creta" },
      { key: "HYUNDAI ELANTRA", value: "Hyundai Elantra" },
      { key: "HYUNDAI ELITE I20", value: "Hyundai Elite i20" },
      { key: "HYUNDAI EON", value: "Hyundai Eon" },
      { key: "HYUNDAI GETZ", value: "Hyundai Getz" },
      { key: "HYUNDAI GETZ PRIME", value: "Hyundai Getz Prime" },
      { key: "HYUNDAI GRAND I10", value: "Hyundai Grand i10" },
      { key: "HYUNDAI I20 ACTIVE", value: "Hyundai i20 Active" },
      { key: "HYUNDAI NEW ELANTRA", value: "Hyundai New Elantra" },
      { key: "HYUNDAI SANTA FE", value: "Hyundai Santa Fe" },
      { key: "HYUNDAI SANTRO", value: "Hyundai Santro" },
      { key: "HYUNDAI NEW SANTRO", value: "Hyundai New Santro" },
      { key: "HYUNDAI SANTRO XING", value: "Hyundai Santro Xing" },
      { key: "HYUNDAI SONATA", value: "Hyundai Sonata" },
      { key: "HYUNDAI SONATA EMBERA", value: "Hyundai Sonata Embera" },
      { key: "HYUNDAI SONATA TRANSFORM", value: "Hyundai Sonata Transform" },
      { key: "HYUNDAI TERRACAN", value: "Hyundai Terracan" },
      { key: "HYUNDAI TUCSON", value: "Hyundai Tucson" },
      { key: "HYUNDAI TUCSON NEW", value: "Hyundai Tucson New" },
      { key: "HYUNDAI XCENT", value: "Hyundai Xcent" },
      { key: "ICML RHINO RX", value: "ICML Rhino RX" },
      { key: "ISUZU D-MAX S-CAB", value: "Isuzu D-MAX S-Cab" },
      { key: "ISUZU D-MAX V CROSS", value: "Isuzu D-MAX V Cross" },
      { key: "ISUZU MU-7", value: "Isuzu MU-7" },
      { key: "ISUZU MU-X", value: "Isuzu MU-X" },
      { key: "JAGUAR F TYPE", value: "Jaguar F-Type" },
      { key: "JAGUAR F-PACE", value: "Jaguar F-Pace" },
      { key: "JAGUAR JAGUAR XF", value: "Jaguar Jaguar XF" },
      { key: "JAGUAR JAGUAR XJ", value: "Jaguar Jaguar XJ" },
      { key: "JAGUAR XE", value: "Jaguar XE" },
      { key: "JAGUAR XF", value: "Jaguar XF" },
      { key: "JAGUAR XJ", value: "Jaguar XJ" },
      { key: "JAGUAR XJ L", value: "Jaguar XJ L" },
      { key: "JAGUAR XK", value: "Jaguar XK" },
      { key: "JEEP COMPASS", value: "Jeep Compass" },
      { key: "JEEP GRAND CHEROKEE", value: "Jeep Grand Cherokee" },
      { key: "LAMBORGHINI AVENTADOR", value: "Lamborghini Aventador" },
      { key: "LAMBORGHINI GALLARDO", value: "Lamborghini Gallardo" },
      { key: "LANDROVER DISCOVERY", value: "Land Rover Discovery" },
      { key: "LANDROVER DISCOVERY 3", value: "Land Rover Discovery 3" },
      { key: "LANDROVER DISCOVERY 4", value: "Land Rover Discovery 4" },
      { key: "LANDROVER DISCOVERY SPORT", value: "Land Rover Discovery Sport" },
      { key: "LANDROVER FREELANDER", value: "Land Rover Freelander" },
      { key: "LANDROVER FREELANDER 2", value: "Land Rover Freelander 2" },
      { key: "LANDROVER RANGE ROVER", value: "Land Rover Range Rover" },
      {
        key: "LANDROVER RANGE ROVER EVOQUE",
        value: "Land Rover Range Rover Evoque",
      },
      {
        key: "LANDROVER RANGE ROVER SPORT",
        value: "Land Rover Range Rover Sport",
      },
      { key: "MAHINDRA ARMADA", value: "Mahindra Armada" },
      { key: "MAHINDRA BOLERO", value: "Mahindra Bolero" },
      { key: "MAHINDRA COMMANDER", value: "Mahindra Commander" },
      { key: "MAHINDRA E 20", value: "Mahindra e2o" },
      { key: "MAHINDRA E20 PLUS", value: "Mahindra e2oPlus" },
      { key: "MAHINDRA JEEP", value: "Mahindra Jeep" },
      { key: "MAHINDRA KUV 100 NXT", value: "Mahindra KUV100 NXT" },
      { key: "MAHINDRA KUV100", value: "Mahindra KUV100" },
      { key: "MAHINDRA MARAZZO", value: "Mahindra Marazzo" },
      { key: "MAHINDRA MARSHAL", value: "Mahindra Marshal" },
      { key: "MAHINDRA MAXX", value: "Mahindra Maxx" },
      { key: "MAHINDRA MAXXIMO", value: "Mahindra Maxximo" },
      { key: "MAHINDRA MAXXIMO 7 SEATER", value: "Mahindra Maxximo 7 Seater" },
      { key: "MAHINDRA MAXXIMO 8 SEATER", value: "Mahindra Maxximo 8 Seater" },
      { key: "MAHINDRA NUVOSPORT", value: "Mahindra Nuvosport" },
      { key: "MAHINDRA QUANTO", value: "Mahindra Quanto" },
      { key: "MAHINDRA RENAULT LOGAN", value: "Mahindra Renault Logan" },
      { key: "MAHINDRA REVA", value: "Mahindra Reva" },
      { key: "MAHINDRA SCORPIO", value: "Mahindra Scorpio" },
      { key: "MAHINDRA SUPRO", value: "Mahindra Supro" },
      { key: "MAHINDRA THAR", value: "Mahindra Thar" },
      { key: "MAHINDRA TUV 300 PLUS", value: "Mahindra TUV300 Plus" },
      { key: "MAHINDRA TUV300", value: "Mahindra TUV300" },
      { key: "MAHINDRA VERITO", value: "Mahindra Verito" },
      { key: "MAHINDRA VERITO VIBE CS", value: "Mahindra Verito Vibe CS" },
      { key: "MAHINDRA VOYEGER", value: "Mahindra Voyeger" },
      { key: "MAHINDRA XUV500", value: "Mahindra XUV500" },
      { key: "MAHINDRA XYLO", value: "Mahindra Xylo" },
      { key: "MARUTI 1000", value: "Maruti 1000" },
      { key: "MARUTI 800", value: "Maruti 800" },
      { key: "MARUTI A STAR", value: "Maruti A-Star" },
      { key: "MARUTI ALTO 800", value: "Maruti Alto 800" },
      { key: "MARUTI ALTO K10", value: "Maruti Alto K10" },
      { key: "MARUTI CELERIO", value: "Maruti Celerio" },
      { key: "MARUTI CELERIO X", value: "Maruti Celerio X" },
      { key: "MARUTI DZIRE", value: "Maruti Dzire" },
      { key: "MARUTI EECO", value: "Maruti Eeco" },
      { key: "MARUTI ERTIGA", value: "Maruti Ertiga" },
      { key: "MARUTI ESTEEM", value: "Maruti Esteem" },
      { key: "MARUTI GRAND VITARA", value: "Maruti Grand Vitara" },
      { key: "MARUTI GYPSY", value: "Maruti Gypsy" },
      { key: "MARUTI IGNIS", value: "Maruti Ignis" },
      { key: "MARUTI KIZASHI", value: "Maruti Kizashi" },
      { key: "MARUTI OMNI", value: "Maruti Omni" },
      { key: "MARUTI OMNI E", value: "Maruti Omni E" },
      { key: "MARUTI RITZ", value: "Maruti Ritz" },
      { key: "MARUTI S CROSS", value: "Maruti S-Cross" },
      { key: "MARUTI SX4", value: "Maruti SX4" },
      { key: "MARUTI VERSA", value: "Maruti Versa" },
      { key: "MARUTI VITARA BREZZA", value: "Maruti Vitara Brezza" },
      { key: "MARUTI WAGON R 1.0", value: "Maruti Wagon R 1.0" },
      { key: "MARUTI WAGON R DUO", value: "Maruti Wagon R Duo" },
      {
        key: "MARUTI WAGON R STINGRAY",
        value: "Maruti Wagon R Stingray",
      },
      { key: "MARUTI ZEN", value: "Maruti Zen" },
      { key: "MARUTI ZEN ESTILO", value: "Maruti Zen Estilo" },
      { key: "MASERATI GHIBLI", value: "Maserati Ghibli" },
      { key: "MASERATI GRANCABRIO", value: "Maserati Grancabrio" },
      { key: "MASERATI GRANTURISMO", value: "Maserati Granturismo" },
      { key: "MASERATI QUATTROPORTE", value: "Maserati Quattroporte" },
      { key: "MAYBACH 57 S", value: "Maybach 57 S" },
      { key: "MAYBACH 62", value: "Maybach 62" },
      { key: "MERCEDES BENZ A CLASS", value: "Mercedes-Benz A Class" },
      { key: "MERCEDES BENZ B CLASS", value: "Mercedes-Benz B Class" },
      { key: "MERCEDES BENZ C CLASS", value: "Mercedes-Benz C Class" },
      { key: "MERCEDES BENZ CLA CLASS", value: "Mercedes-Benz CLA Class" },
      { key: "MERCEDES BENZ CLS", value: "Mercedes-Benz CLA" },
      { key: "MERCEDES BENZ CLS CLASS", value: "Mercedes-Benz Cls Class" },
      { key: "MERCEDES BENZ E CLASS", value: "Mercedes-Benz E Class" },
      { key: "MERCEDES BENZ G CLASS", value: "Mercedes-Benz G Class" },
      { key: "MERCEDES BENZ GL CLASS", value: "Mercedes-Benz GL Class" },
      { key: "MERCEDES BENZ GLA CLASS", value: "Mercedes-Benz GLA Class" },
      { key: "MERCEDES BENZ GLC CLASS", value: "Mercedes-Benz GLC Class" },
      { key: "MERCEDES BENZ GLC COUPE", value: "Mercedes-Benz GLC Coupé" },
      { key: "MERCEDES BENZ GLE", value: "Mercedes-Benz GLE" },
      { key: "MERCEDES BENZ GLS", value: "Mercedes-Benz GLS" },
      { key: "MERCEDES BENZ M CLASS", value: "Mercedes-Benz M Class" },
      {
        key: "MERCEDES BENZ MAYBACH S CLASS",
        value: "Mercedes-Benz May-bach S Class",
      },
      { key: "MERCEDES BENZ ML CLASS", value: "Mercedes-Benz ML Class" },
      { key: "MERCEDES BENZ R CLASS", value: "Mercedes-Benz R Class" },
      { key: "MERCEDES BENZ S CLASS", value: "Mercedes-Benz S Class" },
      { key: "MERCEDES BENZ SDL", value: "Mercedes-Benz SDL" },
      { key: "MERCEDES BENZ SL CLASS", value: "Mercedes-Benz SL Class" },
      { key: "MERCEDES BENZ SLK CLASS", value: "Mercedes-Benz SLK Class" },
      { key: "MERCEDES BENZ SLS CLASS", value: "Mercedes-Benz SLS Class" },
      { key: "MERCEDES BENZ VIANO", value: "Mercedes-Benz Viano" },
      { key: "MERCEDES BENZ W124", value: "Mercedes-Benz W124" },
      { key: "MITSUBISHI CEDIA", value: "Mitsubishi Cedia" },
      { key: "MITSUBISHI LANCER", value: "Mitsubishi Lancer" },
      {
        key: "MITSUBISHI LANCER EVOLUTION",
        value: "Mitsubishi Lancer Evolution",
      },
      { key: "MITSUBISHI MONTERO", value: "Mitsubishi Montero" },
      { key: "MITSUBISHI OUTLANDER", value: "Mitsubishi Outlander" },
      { key: "MITSUBISHI PAJERO", value: "Mitsubishi Pajero" },
      { key: "MITSUBISHI PAJERO SPORT", value: "Mitsubishi Pajero Sport" },
      { key: "NISSAN 370Z", value: "Nissan 370Z" },
      { key: "NISSAN CEDRIC", value: "Nissan Cedric" },
      { key: "NISSAN EVALIA", value: "Nissan Evalia" },
      { key: "NISSAN MICRA", value: "Nissan Micra" },
      { key: "NISSAN MICRA ACTIVE", value: "Nissan Micra Active" },
      { key: "NISSAN MICRA PRIMO", value: "Nissan Micra Primo" },
      { key: "NISSAN SUNNY", value: "Nissan Sunny" },
      { key: "NISSAN TEANA", value: "Nissan Teana" },
      { key: "NISSAN TERRANO", value: "Nissan Terrano" },
      { key: "NISSAN X TRAIL", value: "Nissan X-Trail" },
      { key: "OPEL ASTRA", value: "Opel Astra" },
      { key: "OPEL CORSA", value: "Opel Corsa" },
      { key: "OPEL VECTRA", value: "Opel Vectra" },
      { key: "PORSCHE 911", value: "Porsche 911" },
      { key: "PORSCHE BOXTER", value: "Porsche Boxter" },
      { key: "PORSCHE CAYENNE", value: "Porsche Cayenne" },
      { key: "PORSCHE CAYMAN", value: "Porsche Cayman" },
      { key: "PORSCHE MACAN", value: "Porsche Macan" },
      { key: "PORSCHE PANAMERA", value: "Porsche Panamera" },
      { key: "PORSCHE CARRERA", value: "Porsche Carrera" },
      { key: "PREMIER PADMINI", value: "Premier Padmini" },
      { key: "PREMIER RIO", value: "Premier Rio" },
      { key: "RENAULT CAPTUR", value: "Renault Captur" },
      { key: "RENAULT DUSTER", value: "Renault Duster" },
      { key: "RENAULT FLUENCE", value: "Renault Fluence" },
      { key: "RENAULT KOLEOS", value: "Renault Koleos" },
      { key: "RENAULT LODGY", value: "Renault Lodgy" },
      { key: "RENAULT PULSE", value: "Renault Pulse" },
      { key: "RENAULT SCALA", value: "Renault Scala" },
      { key: "ROLLS ROYCE DAWN", value: "Rolls-Royce Dawn" },
      { key: "ROLLS ROYCE GHOST", value: "Rolls-Royce Ghost" },
      { key: "ROLLS ROYCE PHANTOM", value: "Rolls-Royce Phantom" },
      { key: "ROLLS ROYCE PHANTOM COUPE", value: "Rolls-Royce Phantom Coupé" },
      {
        key: "ROLLS ROYCE PHANTOM DROP HEAD COUPE",
        value: "Rolls-Royce Phantom Drophead Coupé",
      },
      {
        key: "ROLLS ROYCE PHANTOM SERIES II",
        value: "Rolls-Royce Phantom Series II",
      },
      { key: "ROLLS ROYCE WRAITH", value: "Rolls-Royce Wraith" },
      { key: "SAN STORM", value: "San Storm" },
      { key: "SKODA FABIA", value: "Skoda Fabia" },
      { key: "SKODA LAURA", value: "Skoda Laura" },
      { key: "SKODA OCTAVIA", value: "Skoda Octavia" },
      { key: "SKODA OCTAVIA COMBI", value: "Skoda Octavia Combi" },
      { key: "SKODA RAPID", value: "Skoda Rapid" },
      { key: "SKODA SUPERB", value: "Skoda Superb" },
      { key: "SKODA YETI", value: "Skoda Yeti" },
      { key: "SSANGYONG REXTON", value: "SsangYong Rexton" },
      { key: "SUBARU LEGACY", value: "Subaru Legacy" },
      { key: "TATA ARIA", value: "Tata Aria" },
      { key: "TATA BOLT", value: "Tata Bolt" },
      { key: "TATA ESTATE", value: "Tata Estate" },
      { key: "TATA GRANDE DICOR", value: "Tata Grande Dicor" },
      { key: "TATA HEXA", value: "Tata Hexa" },
      { key: "TATA INDICA", value: "Tata Indica" },
      { key: "TATA INDICA EV2", value: "Tata Indica eV2" },
      { key: "TATA INDICA EV2 XETA", value: "Tata Indica eV2 Xeta" },
      { key: "TATA INDICA V2", value: "Tata Indica V2" },
      { key: "TATA INDICA V2 TURBO", value: "Tata Indica V2 Turbo" },
      { key: "TATA INDICA V2 XETA", value: "Tata Indica V2 Xeta" },
      { key: "TATA INDICA VISTA", value: "Tata Indica Vista" },
      { key: "TATA INDICAB", value: "Tata Indicab" },
      { key: "TATA INDIGO", value: "Tata Indigo" },
      { key: "TATA INDIGO CS", value: "Tata Indigo CS" },
      { key: "TATA INDIGO ECS", value: "Tata Indigo eCS" },
      { key: "TATA INDIGO MARINA", value: "Tata Indigo Marina" },
      { key: "TATA INDIGO XL", value: "Tata Indigo XL" },
      { key: "TATA MAGIC", value: "Tata Magic" },
      { key: "TATA MANZA", value: "Tata Manza" },
      { key: "TATA MOVUS", value: "Tata Movus" },
      { key: "TATA NANO", value: "Tata Nano" },
      { key: "TATA NEXON", value: "Tata Nexon" },
      { key: "TATA SAFARI", value: "Tata Safari" },
      { key: "TATA SAFARI STORME", value: "Tata Safari Storme" },
      { key: "TATA SIERRA", value: "Tata Sierra" },
      { key: "TATA SUMO", value: "Tata Sumo" },
      { key: "TATA SUMO GOLD", value: "Tata Sumo Gold" },
      { key: "TATA SUMO GRANDE", value: "Tata Sumo Grande" },
      { key: "TATA TIAGO", value: "Tata Tiago" },
      { key: "TATA TIGOR", value: "Tata Tigor" },
      { key: "TATA TL", value: "Tata TL" },
      { key: "TATA VENTURE", value: "Tata Venture" },
      { key: "TATA VISTA", value: "Tata Vista" },
      { key: "TATA VISTA TECH", value: "Tata Vista Tech" },
      { key: "TATA WINGER", value: "Tata Winger" },
      { key: "TATA XENON XT", value: "Tata Xenon XT" },
      { key: "TATA ZEST", value: "Tata Zest" },
      { key: "TOYOTA CAMRY", value: "Toyota Camry" },
      { key: "TOYOTA CARINA", value: "Toyota Carina" },
      { key: "TOYOTA COROLLA", value: "Toyota Corolla" },
      { key: "TOYOTA COROLLA ALTIS", value: "Toyota Corolla Altis" },
      { key: "TOYOTA ETIOS", value: "Toyota Etios" },
      { key: "TOYOTA ETIOS LIVA", value: "Toyota Etios Liva" },
      { key: "TOYOTA FORTUNER", value: "Toyota Fortuner" },
      { key: "TOYOTA HIACE VAN", value: "Toyota Hiace Van" },
      { key: "TOYOTA INNOVA", value: "Toyota Innova" },
      { key: "TOYOTA INNOVA CRYSTA", value: "Toyota Innova Crysta" },
      { key: "TOYOTA LAND CRUISER", value: "Toyota Land Cruiser" },
      { key: "TOYOTA LAND CRUISER PRADO", value: "Toyota Land Cruiser Prado" },
      { key: "TOYOTA LEXUS", value: "Toyota Lexus" },
      { key: "TOYOTA PRIUS", value: "Toyota Prius" },
      { key: "TOYOTA QUALIS", value: "Toyota Qualis" },
      { key: "TOYOTA STARLET", value: "Toyota Starlet" },
      { key: "TOYOTA YARIS", value: "Toyota Yaris" },
      { key: "VOLKSWAGEN AMEO", value: "Volkswagen Ameo" },
      { key: "VOLKSWAGEN BEETLE", value: "Volkswagen Beetle" },
      { key: "VOLKSWAGEN CARAVELLE", value: "Volkswagen Caravelle" },
      { key: "VOLKSWAGEN CROSS POLO", value: "Volkswagen Cross Polo" },
      { key: "VOLKSWAGEN JETTA", value: "Volkswagen Jetta" },
      { key: "VOLKSWAGEN PASSAT", value: "Volkswagen Passat" },
      { key: "VOLKSWAGEN PHAETON", value: "Volkswagen Phaeton" },
      { key: "VOLKSWAGEN TIGUAN", value: "Volkswagen Tiguan" },
      { key: "VOLKSWAGEN TOUAREG", value: "Volkswagen Touareg" },
      { key: "VOLKSWAGEN VENTO", value: "Volkswagen Vento" },
      { key: "VOLVO S60", value: "Volvo S60" },
      { key: "VOLVO S80", value: "Volvo S80" },
      { key: "VOLVO S90", value: "Volvo S90" },
      { key: "VOLVO V 40", value: "Volvo V40" },
      { key: "VOLVO V40 CROSS COUNTRY", value: "Volvo V40 Cross Country" },
      { key: "VOLVO XC 60", value: "Volvo XC60" },
      { key: "VOLVO XC 90", value: "Volvo XC90" },
      { key: "VOLVO", value: "Volvo" },
      { key: "JAGUAR", value: "Jaguar" },
      { key: "BENTLEY", value: "Bentley" },
      { key: "PORSCHE", value: "Porsche" },
      { key: "FERRARI", value: "Ferrari" },
      { key: "ASTON MARTIN", value: "Aston Martin" },
      { key: "LAMBORGHINI", value: "Lamborghini" },
      { key: "MITSUBISHI", value: "Mitsubishi" },
    ],
  },
];
